### ISSUE TITLE
can't get url

### ISSUE THREAD

**Issue by Hunlongyu** [freearhey/iptv-playlist-parser#15]
https://raw.githubusercontent.com/LITUATUI/M3UPT/main/m3upt.m3u
![image](https://user-images.githubusercontent.com/15273630/153429921-bc10060e-7873-4d08-bf25-99fa985a3520.png)

**Comment by freearhey** [comment]
Fixed in [v0.11.0](https://github.com/freearhey/iptv-playlist-parser/releases/tag/v0.11.0)

**Comment by Hunlongyu** [comment]
Nice~
