### ISSUE TITLE
Playlist.stringify() 

### ISSUE THREAD

**Issue by edelciomolina** [freearhey/iptv-playlist-parser#17]
What about a method for to reconstruct a m3u file from the Playlist object?
```ts
....
const result: Playlist = parser.parse(playlist)
const playlistRaw: String = result.Stringify()  // As suggestion!
```
If you do not have a way to do this, I can contribute with a pull request. Let me know, because is a feature that I need 😉

**Comment by freearhey** [comment]
Why not just use the `playlist` variable?

**Comment by edelciomolina** [comment]
@freearhey Sure, in this context above, yes.
But now think about after the `result` variable is changed (is what I'm doing here), after that I need to reconstruct a string variable to save as a `.m3u` file.

**Comment by freearhey** [comment]
In this case you'd better use a utility like [Raiper34/m3u-parser-generator](https://github.com/Raiper34/m3u-parser-generator), which already includes a playlist generator. And I do not plan to include this functionality in the `iptv-playlist-parser`.
