### ISSUE TITLE
iptv-playlist-parser on ionic

### ISSUE THREAD

**Issue by elmasky** [freearhey/iptv-playlist-parser#2]
hello,

how can we use this package in ionic ? 

in import we have : Could not find a declaration file for module 'iptv-playlist-parser'.

**Comment by freearhey** [comment]
To be honest, I don't know exactly what the problem could be, but it seems to have something to do with TypeScript. If so, it might be worth trying this solution: https://github.com/microsoft/TypeScript/issues/15031#issuecomment-291957621

**Comment by freearhey** [comment]
Recently, TypeScript support has been added to the library (#5), which should solve this problem.

Please create a new issue if the error does not disappear.
