### ISSUE TITLE
\r\n

### ISSUE THREAD

**Issue by daneldanel** [freearhey/iptv-playlist-parser#7]
Sample input:
"#EXTM3U\r\n#EXTINF: -1, name\r\nhttp://100.101.102.103:1000/index.m3u8\r\n"

Output:
{ header: { attrs: {}, raw: '#EXTM3U' },
  items:
   [ { name: ' name\r',
       tvg: [Object],
       group: [Object],
       http: [Object],
       url: 'http://100.101.102.103:1000/index.m3u8',
       raw:
        '#EXTINF: -1, name\r\nhttp://100.101.102.103:1000/index.m3u8' } ] }

In the result:
name: ' name\r'

Expected result:
name: ' name'

**Comment by freearhey** [comment]
Fixed in [v0.5.1](https://github.com/freearhey/iptv-playlist-parser/releases/tag/v0.5.1)
