### ISSUE TITLE
For large playlists, this will block your node while parsing

### ISSUE THREAD

**Issue by San-Jeevan** [freearhey/iptv-playlist-parser#9]
I have playlist with 54 000 items.
It freezes entire node for 10-12 seconds during parsing.

**Comment by freearhey** [comment]
And do you know how to avoid that?

**Comment by San-Jeevan** [comment]
I tried putting the code in a Promise, but it didnt help. If i come up with a fix i will let u know

**Comment by alectrocute** [comment]
Obviously you'd want to run this on a different process, or spawn a new one for the task... @San-Jeevan
